### ISSUE TITLE
Add resources for Job templates

### ISSUE THREAD

**Issue by alesuiss** [ONLYOFFICE/Kubernetes-Docs#177]
Hello,

Our Openshift cluster rejects anything that doesn't have `resources.limits.memory` set; currently that means that install/upgrade/rollback/delete jobs don't work for us. It would be nice to add the option to specify `resources` for the jobs.

Cheers,
Arthur

**Comment by GeorgeONLYOFFICE** [comment]
Hello, we can add it no problem, however some modifications will be required on your end with regards to [this PR](https://github.com/ONLYOFFICE/Kubernetes-Docs/pull/178)


Please make it in accordance with how it's done for Deployement, i.e. [here](https://github.com/ONLYOFFICE/Kubernetes-Docs/blob/master/values.yaml#L113-L122)

So, basically, you need to add this into values.yaml
```
    resources:
      ##Example:
      ##requests:
      ##  memory: "256Mi"
      ##  cpu: "100m"
      requests: {}
      ##limits:
      ##  memory: "256Mi"
      ##  cpu: "100m"
      limits: {}
```
The other PR of yours will be merged as it is.
