### ISSUE TITLE
pre-install ImagePullBackOff

### ISSUE THREAD

**Issue by zhangwei900808** [ONLYOFFICE/Kubernetes-Docs#323]
I used helm install onlyoffice and run in github actions but console ImagePullBackOff

values.yaml
```
connections:
#  amqpExistingSecret: rabbitmq
  amqpHost: rabbitmq-headless.rabbit.svc.cluster.local
  amqpPassword: "xxx"
  amqpPort: "5672"
  amqpProto: amqp
#  amqpSecretKeyName: rabbitmq-password
  amqpType: rabbitmq
  amqpUser: user
  amqpVhost: /

#  dbExistingSecret: postgresql
  dbHost: xxx.com
  dbName: onlyoffice
# Database user password. If set to, it takes priority over the connections.dbExistingSecret 属性
  dbPassword: "xxx"
  dbPort: "3306"
#  dbSecretKeyName: postgres-password
  dbType: mysql
  dbUser: awbeci

#  redisClusterNodes: []
  redisConnectorName: redis
  redisDBNum: "1"
#  redisExistingSecret: redis
  redisHost: xxx.com
#  redisNoPass: false
  redisPassword: "xxx"
  redisPort: "6379"
#  redisSecretKeyName: redis-password
#  redisSentinelGroupName: mymaster
  redisUser: default
persistence:
  size: 8Gi
  storageClass: alibabacloud-cnfs-nas
service:
  port: 8888
  type: NodePort
```

github actions 
```
name: Deploy OnlyOffice CI

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main
#    tags:
#      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Kubernetes (configure kubeconfig)
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
#        with:
#          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      # Step 3: Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # Step 4: Add OnlyOffice Helm repo (if required)
      - name: Add OnlyOffice Helm repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add onlyoffice https://download.onlyoffice.com/charts/stable

      # Step 5: Update Helm repos
      - name: Update Helm repos
        run: helm repo update

      - name: Uninstall existing OnlyOffice release (if exists)
        run: |
          helm uninstall onlyoffice --namespace onlyoffice || true

      # Step 6: Install OnlyOffice using Helm
      - name: Install OnlyOffice
        run: |
          kubectl get namespace onlyoffice || kubectl create namespace onlyoffice
          helm install onlyoffice onlyoffice/docs -f helm/onlyoffice/values.yaml --namespace onlyoffice

```

console
```
➜  k get all -nonlyoffice
NAME                    READY   STATUS             RESTARTS   AGE
pod/pre-install-gs9l6   0/1     ImagePullBackOff   0          12h

NAME                    COMPLETIONS   DURATION   AGE
job.batch/pre-install   0/1           12h        12h
```
